import { PERMISSIONS, Permission } from "@/lib/auth/permissions";

const ADAPTER_PERMISSIONS: Record<string, Permission> = {
    mysql: PERMISSIONS.SOURCES.VIEW,
    mariadb: PERMISSIONS.SOURCES.VIEW,
    postgres: PERMISSIONS.SOURCES.VIEW,
    mongodb: PERMISSIONS.SOURCES.VIEW,
    sqlite: PERMISSIONS.SOURCES.VIEW,
    mssql: PERMISSIONS.SOURCES.VIEW,
    redis: PERMISSIONS.SOURCES.VIEW,

    "local-filesystem": PERMISSIONS.DESTINATIONS.READ,
    "s3-generic": PERMISSIONS.DESTINATIONS.READ,
    "s3-aws": PERMISSIONS.DESTINATIONS.READ,
    "s3-r2": PERMISSIONS.DESTINATIONS.READ,
    "s3-hetzner": PERMISSIONS.DESTINATIONS.READ,
    sftp: PERMISSIONS.DESTINATIONS.READ,
    smb: PERMISSIONS.DESTINATIONS.READ,
    webdav: PERMISSIONS.DESTINATIONS.READ,
    ftp: PERMISSIONS.DESTINATIONS.READ,
    rsync: PERMISSIONS.DESTINATIONS.READ,
    "google-drive": PERMISSIONS.DESTINATIONS.READ,
    dropbox: PERMISSIONS.DESTINATIONS.READ,
    onedrive: PERMISSIONS.DESTINATIONS.READ,

    discord: PERMISSIONS.NOTIFICATIONS.READ,
    slack: PERMISSIONS.NOTIFICATIONS.READ,
    teams: PERMISSIONS.NOTIFICATIONS.READ,
    "generic-webhook": PERMISSIONS.NOTIFICATIONS.READ,
    gotify: PERMISSIONS.NOTIFICATIONS.READ,
    ntfy: PERMISSIONS.NOTIFICATIONS.READ,
    telegram: PERMISSIONS.NOTIFICATIONS.READ,
    "twilio-sms": PERMISSIONS.NOTIFICATIONS.READ,
    email: PERMISSIONS.NOTIFICATIONS.READ,
};

export function getPermissionForAdapter(adapterId: string): Permission | null {
    return ADAPTER_PERMISSIONS[adapterId] ?? null;
}
