/**
 * Types for the system notification framework.
 *
 * System notifications are sent for configurable events (e.g. user login,
 * backup completion) through user-selected notification channels
 * (Email, Discord, etc.).
 */

/** All supported system notification event types */
export const NOTIFICATION_EVENTS = {
  USER_LOGIN: "user_login",
  USER_CREATED: "user_created",
  BACKUP_SUCCESS: "backup_success",
  BACKUP_FAILURE: "backup_failure",
  RESTORE_COMPLETE: "restore_complete",
  RESTORE_FAILURE: "restore_failure",
  CONFIG_BACKUP: "config_backup",
  SYSTEM_ERROR: "system_error",
  STORAGE_USAGE_SPIKE: "storage_usage_spike",
  STORAGE_LIMIT_WARNING: "storage_limit_warning",
  STORAGE_MISSING_BACKUP: "storage_missing_backup",
  UPDATE_AVAILABLE: "update_available",
  CONNECTION_OFFLINE: "connection_offline",
  CONNECTION_ONLINE: "connection_online",
  DB_VERSION_CHANGED: "db_version_changed",
  INTEGRITY_CHECK_FAILURE: "integrity_check_failure",
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

/**
 * Controls who receives a notification for user-specific events.
 * - "none"  – Only configured channels (admin channels)
 * - "also"  – Configured channels AND a direct email to the user
 * - "only"  – Only a direct email to the user (no admin channels)
 */
export type NotifyUserMode = "none" | "also" | "only";

/** Metadata describing a notification event */
export interface NotificationEventDefinition {
  id: NotificationEventType;
  name: string;
  description: string;
  category: "auth" | "backup" | "restore" | "system" | "storage" | "updates" | "health";
  /** Default enabled state when first configured */
  defaultEnabled: boolean;
  /**
   * When true, this event carries a user email address and can send
   * a direct notification to the affected user (only via Email/SMTP adapters).
   */
  supportsNotifyUser?: boolean;
  /**
   * When true, this event supports configurable reminder intervals.
   * The notification will be re-sent after the configured interval while the condition persists.
   */
  supportsReminder?: boolean;
}

/** Payload generated by a template for adapter consumption */
export interface NotificationPayload {
  /** Short title (email subject, embed title, etc.) */
  title: string;
  /** Plain text message body */
  message: string;
  /** Structured fields for rich display (embeds, tables) */
  fields?: Array<{ name: string; value: string; inline?: boolean }>;
  /** Hex color for embeds / status indicators */
  color?: string;
  /** Whether the event represents a success or failure */
  success: boolean;
  /** Optional badge label override (e.g. "Alert") - replaces auto-detected status badge in emails */
  badge?: string;
}

/** Data passed to template functions per event type */
export interface UserLoginData {
  userName: string;
  email: string;
  ipAddress?: string;
  userAgent?: string;
  timestamp: string;
}

export interface UserCreatedData {
  userName: string;
  email: string;
  createdBy?: string;
  timestamp: string;
}

export interface BackupResultData {
  jobName: string;
  sourceName?: string;
  duration?: number;
  size?: number;
  error?: string;
  executionId?: string;
  timestamp: string;
}

export interface RestoreResultData {
  sourceName?: string;
  targetDatabase?: string;
  databaseType?: string;
  backupFile?: string;
  storageName?: string;
  size?: number;
  duration?: number;
  error?: string;
  executionId?: string;
  timestamp: string;
}

export interface ConfigBackupData {
  fileName?: string;
  size?: number;
  encrypted: boolean;
  timestamp: string;
}

export interface SystemErrorData {
  component: string;
  error: string;
  details?: string;
  timestamp: string;
}

export interface StorageUsageSpikeData {
  storageName: string;
  previousSize: number;
  currentSize: number;
  changePercent: number;
  timestamp: string;
}

export interface StorageLimitWarningData {
  storageName: string;
  currentSize: number;
  limitSize: number;
  usagePercent: number;
  timestamp: string;
}

export interface StorageMissingBackupData {
  storageName: string;
  lastBackupAt?: string;
  thresholdHours: number;
  hoursSinceLastBackup: number;
  timestamp: string;
}

export interface UpdateAvailableData {
  latestVersion: string;
  currentVersion: string;
  releaseUrl?: string;
  timestamp: string;
}

export interface ConnectionOfflineData {
  adapterName: string;
  adapterType: "database" | "storage";
  adapterId: string;
  consecutiveFailures: number;
  lastError?: string;
  timestamp: string;
}

export interface ConnectionOnlineData {
  adapterName: string;
  adapterType: "database" | "storage";
  adapterId: string;
  downtime?: string;
  timestamp: string;
}

export interface DbVersionChangedData {
  sourceName: string;
  sourceId: string;
  adapterId: string;
  previousVersion: string | null;
  newVersion: string;
  edition?: string;
  timestamp: string;
  isDowngrade: boolean;
}

export interface IntegrityCheckFailureData {
  totalFiles: number;
  failed: number;
  passed: number;
  skipped: number;
  triggerType: "Scheduler" | "Manual";
  errors: Array<{
    file: string;
    destination: string;
    expected: string;
    actual: string;
  }>;
}

/** Union of all event data types for type-safe template dispatch */
export type NotificationEventData =
  | { eventType: typeof NOTIFICATION_EVENTS.USER_LOGIN; data: UserLoginData }
  | { eventType: typeof NOTIFICATION_EVENTS.USER_CREATED; data: UserCreatedData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_SUCCESS; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.BACKUP_FAILURE; data: BackupResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.RESTORE_COMPLETE; data: RestoreResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.RESTORE_FAILURE; data: RestoreResultData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONFIG_BACKUP; data: ConfigBackupData }
  | { eventType: typeof NOTIFICATION_EVENTS.SYSTEM_ERROR; data: SystemErrorData }
  | { eventType: typeof NOTIFICATION_EVENTS.STORAGE_USAGE_SPIKE; data: StorageUsageSpikeData }
  | { eventType: typeof NOTIFICATION_EVENTS.STORAGE_LIMIT_WARNING; data: StorageLimitWarningData }
  | { eventType: typeof NOTIFICATION_EVENTS.STORAGE_MISSING_BACKUP; data: StorageMissingBackupData }
  | { eventType: typeof NOTIFICATION_EVENTS.UPDATE_AVAILABLE; data: UpdateAvailableData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONNECTION_OFFLINE; data: ConnectionOfflineData }
  | { eventType: typeof NOTIFICATION_EVENTS.CONNECTION_ONLINE; data: ConnectionOnlineData }
  | { eventType: typeof NOTIFICATION_EVENTS.DB_VERSION_CHANGED; data: DbVersionChangedData }
  | { eventType: typeof NOTIFICATION_EVENTS.INTEGRITY_CHECK_FAILURE; data: IntegrityCheckFailureData };

/** Persisted notification configuration (stored as JSON in SystemSetting) */
export interface SystemNotificationConfig {
  /** Default channel IDs (AdapterConfig IDs) used when event has no override */
  globalChannels: string[];
  /** Per-event settings */
  events: Record<
    string,
    {
      enabled: boolean;
      /** Override channels for this event. null = use globalChannels */
      channels: string[] | null;
      /** Whether to also/only send a direct email to the affected user */
      notifyUser?: NotifyUserMode;
      /** Reminder interval in hours. When set, re-sends notification after this period while condition persists. */
      reminderIntervalHours?: number | null;
    }
  >;
}
